# -*- coding: utf-8 -*-
"""Read Data and First Map .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MzYyY_sd4zClNo4oKCpLor0SJjoLfuPJ

# **Theory Part**

Course from: [kaggle.com](https://www.kaggle.com/code/alexisbcook/your-first-map/tutorial)
"""

# Module to clear unnecessary output
from google.colab import output

# Installing geopandas library
!pip install geopandas
output.clear()

# Importing geopandas 
import geopandas as gpd

# UnZip files .zip to create new files
!unzip DEC_lands.zip -d DEC_lands
output.clear()

# Read in the data
full_data = gpd.read_file("DEC_lands/DEC_lands.shp")

# View the first five rows of the data
full_data.head()

# Data Type
type(full_data)

# Create a copy of specific columns
data = full_data.loc[:, ["CLASS", "COUNTY", "geometry"]].copy()

# How many lands of each type are there?
data.CLASS.value_counts()

# Select lands that fall under the "WILD FOREST" or "WILDERNESS" category
wild_lands = data.loc[data.CLASS.isin(['WILD FOREST', 'WILDERNESS'])].copy()
wild_lands.head()

# Importing matplotlib to show() plots
import matplotlib.pyplot as plt

# Plotting wild lands
wild_lands.plot()
plt.show()

# View the first five entries in the "geometry" column
wild_lands.geometry.head()

# UnZip files .zip to create new files
!unzip DEC_pointsinterest.zip -d DEC_pointsinterest
!unzip DEC_roadstrails.zip -d DEC_roadstrails
!unzip NY_county_boundaries.zip -d NY_county_boundaries
output.clear()

# Campsites in New York state (Point)
POI_data = gpd.read_file("/content/DEC_pointsinterest/DEC_pointsinterest/DEC_pointsinterest/Decptsofinterest.shp")
campsites = POI_data.loc[POI_data.ASSET=='PRIMITIVE CAMPSITE'].copy()

# Foot trails in New York state (LineString)
roads_trails = gpd.read_file("/content/DEC_roadstrails/DEC_roadstrails/DEC_roadstrails/Decroadstrails.shp")
trails = roads_trails.loc[roads_trails.ASSET=='FOOT TRAIL'].copy()

# County boundaries in New York state (Polygon)
counties = gpd.read_file("/content/NY_county_boundaries/NY_county_boundaries/NY_county_boundaries/NY_county_boundaries.shp")

# Define a base map with county boundaries
ax = counties.plot(figsize = (10, 10), color = 'none',
                   edgecolor = 'gainsboro', zorder = 3)

# Add wild lands, campsites, and foot trails to the base map
wild_lands.plot(color='lightgreen', ax=ax)
campsites.plot(color='maroon', markersize=2, ax=ax)
trails.plot(color='black', markersize=1, ax=ax)
plt.show()

"""# **Example**"""

!unzip kiva_loans.zip -d kiva_loans
output.clear()

loans_filepath = "kiva_loans/kiva_loans/kiva_loans/kiva_loans.shp"

# Load the data
world_loans = gpd.read_file(loans_filepath)

# The first five rows of the data
world_loans.head()

# This dataset is provided in GeoPandas --- WORLD GEOMETRY :o

world_filepath = gpd.datasets.get_path('naturalearth_lowres')
world = gpd.read_file(world_filepath)
world.head()

# Plot of Kiva loan locations across the world.
ax = world.plot(figsize = (10, 10), color = 'none',
                   edgecolor = 'gainsboro', zorder = 3)
world_loans.plot(markersize=2, ax=ax)
plt.show()

# Kiva loans in Philippines only
PHL_loans = world_loans[world_loans['country']=='Philippines'].copy()

# Load a KML file containing island boundaries
gpd.io.file.fiona.drvsupport.supported_drivers['KML'] = 'rw'
PHL = gpd.read_file("Philippines_AL258.kml", driver='KML')
PHL.head()

# Visualization of loans in the Philippines
ax = PHL.plot(figsize=(10,10), color='None',
              edgecolor='gainsboro', zorder=3)

PHL_loans.plot(markersize=2, ax=ax)
plt.show()